trigger: none

pr:
  branches:
    include:
      - main
  paths:
    exclude:
      - '**/*.README.md'
      - 'README.md'

resources:
  repositories:
    - repository: templates
      type: github
      name: liam-goodchild/pipeline-engineering-templates
      endpoint: liam-goodchild
      ref: refs/heads/main

pool:
  vmImage: ubuntu-latest

stages:
  # Stage 1: Linting
  - stage: Linting
    displayName: 'Linting & Validation'
    jobs:
      - job: SuperLinter
        displayName: 'Super-Linter'
        steps:
          - template: validation/linting.yaml@templates
            parameters:
              prettierConfigFile: .azuredevops/linters/.prettierrc.json
              checkovConfigFile: .azuredevops/linters/.checkov.yaml
